name: docs
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/integration_tests.yml
      - '**.py'
      - '**.ipynb'
      - '**.html'
      - '**.js'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'true'

      - name: Install uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build docs
        run: |
          cd docs && rm -rf source/reference/api/_autosummary && uv run make html
          # cd .. && uv run coverage run -m pytest -m "not integration_test" && uv run coverage xml && uv run coverage report -m

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: VectorInstitute/AtomGen
      #     fail_ci_if_error: true
      #     verbose: true

      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: github_pages
          folder: docs/build/html
